// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBArrETIwtt6GLCAW-kEOX54jIJAtEezVw',
    appId: '1:229001548947:web:6fd1cf8bffd90481262966',
    messagingSenderId: '229001548947',
    projectId: 'flutterapp-90d28',
    authDomain: 'flutterapp-90d28.firebaseapp.com',
    storageBucket: 'flutterapp-90d28.appspot.com',
    measurementId: 'G-5GKMF8H76W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLWg6_lvUzcBzDDNRT8keW6aBLmTNcldo',
    appId: '1:229001548947:android:efb2736ceb0fc19f262966',
    messagingSenderId: '229001548947',
    projectId: 'flutterapp-90d28',
    storageBucket: 'flutterapp-90d28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZqV8pV1CzHJK6_y_rz5QvbIt7UfeaIgA',
    appId: '1:229001548947:ios:89049badb89998dc262966',
    messagingSenderId: '229001548947',
    projectId: 'flutterapp-90d28',
    storageBucket: 'flutterapp-90d28.appspot.com',
    iosClientId: '229001548947-k1v333b2vsvk64cpllrmv4e01gub9ep9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPooApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZqV8pV1CzHJK6_y_rz5QvbIt7UfeaIgA',
    appId: '1:229001548947:ios:89049badb89998dc262966',
    messagingSenderId: '229001548947',
    projectId: 'flutterapp-90d28',
    storageBucket: 'flutterapp-90d28.appspot.com',
    iosClientId: '229001548947-k1v333b2vsvk64cpllrmv4e01gub9ep9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPooApi',
  );
}
